name: PBM
version: 1.2
description: PIWCS Backup Manager
author: Javapony

main: ru.windcorp.piwcs.pbm.PBMPlugin

commands:
   backup:
     description: Creates a backup
     usage: backup
  